carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.cart, name='cart'),
    path('<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('<slug>/', views.add_to_cart, name='add_to_cart'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('carts/', include('carts.urls')),
    path('checkout/', include('orders.urls')),
    path('accounts/', include('accounts.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('s/', views.search, name='search'),
    path('all_product/', views.all_products, name='all_product'),
    path('<slug>/', views.single, name='single'),

]

products/models.py
from django.urls import reverse
from django.db import models


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    price = models.IntegerField()
    sale_price = models.IntegerField(default=100)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ('title', 'slug')

    def get_price(self):
        return self.price

    def get_absolute_url(self):
        return reverse('single', kwargs={'slug': self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/')
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.product.title


class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')


VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
    ('package', 'package')
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.CharField(
        max_length=120, choices=VAR_CATEGORIES, default='size')
    title = models.CharField(max_length=120)
    image = models.ForeignKey(ProductImage, blank=True,
                              null=True, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=100, decimal_places=2, blank=True, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    objects = VariationManager()

    def __str__(self):
        return self.title

products/views.py
from django.shortcuts import render, Http404
from .models import Product, ProductImage
from marketing.models import MarketingMessage

# Create your views here.


def search(request):
    try:
        k = request.GET.get('k')
    except:
        k = None
    if k:
        products = Product.objects.filter(title__icontains=k)
        return render(request, 'products/results.html', {
            'query': k,
            'products': products,
        })
    else:
        return render(request, 'products/results.html')


def index(request):
    products = Product.objects.all()
    marketing_message = MarketingMessage.objects.all()[0]
    return render(request, 'products/index.html', {
        'products': products,
        'marketing_message': marketing_message
    })


def all_products(request):
    products = Product.objects.all()
    return render(request, 'products/all_product.html', {
        'products': products
    })


def single(request, slug):
    try:
        product = Product.objects.get(slug=slug)
        images = ProductImage.objects.filter(product=product)
        return render(request, 'products/single.html', {
            'product': product,
            'images': images
        })

    except:
        raise Http404

templates/products/all_product.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="page-header">
  <h1>All Products</h1>
</div>
<section class="content">
  <div class="card card-solid">
    <div class="card-body pb-0">
      <div class="row d-flex align-items-stretch">
        {% for product in products %}
        {% if product.productimage_set.all %}
        {% for item in product.productimage_set.all %}
        <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
          <div class="card">
            <img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h5>
              <p class="card-text">{{ product.price }}</p>
            </div>
            <div>
              <input type="button" value="View" class="btn btn-outline-secondary  mb-2">
              <input type="button" value="Add" class="btn btn-outline-secondary  mb-2 float-right">
            </div>
            <div class="card-footer">
              <small class="text-muted">{{ product.updated }}</small>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
          <div class="card">
            <img class="card-img-top" src="{% static 'img/empty.png' %}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h5>
              <p class="card-text">{{ product.price }}</p>
            </div>
            <div>
              <input type="button" value="View" class="btn btn-outline-secondary  mb-2">
              <input type="button" value="Add" class="btn btn-outline-secondary  mb-2 float-right">
            </div>
            <div class="card-footer">
              <small class="text-muted">{{ product.updated }}</small>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <nav aria-label="Contacts Page Navigation">
        <ul class="pagination justify-content-center m-0">
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">4</a></li>
          <li class="page-item"><a class="page-link" href="#">5</a></li>
          <li class="page-item"><a class="page-link" href="#">6</a></li>
          <li class="page-item"><a class="page-link" href="#">7</a></li>
          <li class="page-item"><a class="page-link" href="#">8</a></li>
        </ul>
      </nav>
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->
</section>
{% endblock %}



{% block jquery %}

{% endblock %}

templates/products/index.html
{% extends 'base/base.html' %}

<!-- slider -->
{% block jumbotron %}
  <div class="container-fluid slider p-0 m-0">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="https://cdn.pixabay.com/photo/2015/10/12/15/18/store-984393_960_720.jpg" alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>This is first slide</h5>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://cdn.pixabay.com/photo/2015/11/07/11/46/fashion-1031469_960_720.jpg" alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>This is second slide</h5>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://cdn.pixabay.com/photo/2017/08/05/00/12/people-2581913_960_720.jpg" alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>This is third slide</h5>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://cdn.pixabay.com/photo/2015/11/07/11/46/fashion-1031469_960_720.jpg" alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>This is fourth slide</h5>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
{% endblock  %}
<!-- end slider -->

{% block content %}
<div class="page-header">
  <h1>Feature Products</h1>
</div>

<section class="content">
  <div class="card card-solid">
    <div class="card-body pb-0">
      <div class="row d-flex align-items-stretch">
        {% for product in products %}
          {% for item in product.productimage_set.all %}
            {% if item.featured %}
              <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
                <div class="card">
                    <img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
                    <div class="card-body">
                      <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></h5>
                      <p class="card-text">Price:{{ product.price }}</p>
                    </div>
                    <div>
                      <input type="button" value="View" class="btn btn-outline-secondary  mb-2" >
                      <input type="button" value="Add" class="btn btn-outline-secondary  mb-2 float-right" >
                    </div>
                    <div class="card-footer">
                      <small class="text-muted">Last-update: {{ product.updated }}</small>
                    </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
        {% endfor %}
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <nav aria-label="Contacts Page Navigation">
        <ul class="pagination justify-content-center m-0">
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">4</a></li>
          <li class="page-item"><a class="page-link" href="#">5</a></li>
          <li class="page-item"><a class="page-link" href="#">6</a></li>
          <li class="page-item"><a class="page-link" href="#">7</a></li>
          <li class="page-item"><a class="page-link" href="#">8</a></li>
        </ul>
      </nav>
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->
</section>
{% endblock %}



{% block jquery %}
           
{% endblock %}

templates/products/results.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<table class="table">
    <thead>
        <th></th>
        <th>Product</th>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td style="height: 160px; width: 160px;">
                {% if product.productimage_set.all %}
                    {% for item in product.productimage_set.all %}
                        {% if item.featured %}
                        <a href="{{ product.get_absolute_url }}">
                            <div style="height: 100%; width:100%; background-image: url('{{ item.image.url }}');  background-size: cover; background-position: center;">

                            </div>
                        </a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                <div class="background-thumb" style="height: 100%; width:100%; background-repeat: no-repeat; background-size: cover; background-position: center;">

                </div>
                {% endif %}
            </td>
            <td><a href="{{ product.get_absolute_url }}">{{ product }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/products/single.html
{% extends 'base/base.html' %}

{% block content %}

<div class="row mt-5">
  <div class="col-sm-4">
    {% for img in images %}
    {% if img.featured %}
    <div class="col-xs-12 col-sm-6">
      <img class="img-thumbnail" src="{{ img.image.url }}" alt="single image">
    </div>
    {% endif %}
    {% endfor %}
    <br>
    <br>

    {% for img in images %}
    {% if not img.featured %}
    <div class="col-xs-6 col-sm-3>
        <a href="#">
      <img class="img-thumbnail" src="{{ img.image.url }}" alt="thumbnail-img">
      </a>
    </div>
    {% endif %}
    {% endfor %}
  </div>
  <div class="col-sm-8">
    <div class="page-header">
      <div class="col-sm-8 float-left" style="padding-left: 0px;">
        <h1>{{ product.title }} </h1>
      </div>
      <div class="col-sm-4 float-right">
        <form action="{% url 'add_to_cart' product.slug %}" method="POST" class="form float-right">
          {% csrf_token %}
          <input type="submit" value="Add To Cart" class="btn btn-info btn-block">
          <input type="number" name="qty" value='1' class="form-control">

          <!-- Size -->
          {% if product.variation_set.all %}

          {% if product.variation_set.sizes %}
          <select name="size" id="" class="form-control">
            {% for item in product.variation_set.sizes %}
            <option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
            {% endfor %}
          </select>
          {% endif %}

          {% if product.variation_set.colors %}
          <select name="color" id="" class="form-control">
            {% for item in product.variation_set.colors %}
            <option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
            {% endfor %}
          </select>
          {% endif %}

          {% endif %}
        </form>
      </div>
    </div>
    <div>
      <p>price: {{ product.price }}.Tk <br>
        Shpping: Free with tk 50+ purchase. </p>
    </div>

    <div>
      {{ product.description | linebreaks }}
    </div>
  </div>
</div>

{% endblock %}